### ISSUE TITLE
Sweep: Add a test for server side OCR workflow

### ISSUE THREAD

**Issue by holdenk** [totallylegitco/fighthealthinsurance#33]
We have existing selenium tests so we could either add the tests with selenium and a random image with some text or we could write a proper django test.

<details open>
<summary>Checklist</summary>

- [X] Create `tests/sample_ocr_image.png` ✓ https://github.com/totallylegitco/fighthealthinsurance/commit/f19cd04d82cba9126f1a94170a7c64e56a69d6d9
- [X] Running GitHub Actions for `tests/sample_ocr_image.png` ✓
- [X] Modify `tests/test_selenium_appeal_generation.py` ✓ https://github.com/totallylegitco/fighthealthinsurance/commit/a4c1ab1abed04b9d64737dc6598b57c3013a0aaa
- [X] Running GitHub Actions for `tests/test_selenium_appeal_generation.py` ✓

![Flowchart](https://raw.githubusercontent.com/totallylegitco/fighthealthinsurance/sweep/assets/1388aeb1c7c7e943255eb52be5e0794c71df649959a25011f5668b52d92fdefd_33_flowchart.svg)
</details>

**Comment by wwzeng1** [comment]
Hi @holdenk! I noticed this failed so I'm retrying it for you :D
